# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20160208_1751'),
        ('users', '0015_auto_20160312_2114'),
    ]

    operations = [
    ]
